import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/ui/Header";
import PageContainer from "@/components/ui/PageContainer";
import { LoaderProvider } from "@/components/ui/LoaderContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LoaderProvider>
          <Header />
          <PageContainer>{children}</PageContainer>
        </LoaderProvider>
      </body>
    </html>
  );
}
